name: Deploy Image to GHCR

on:
  push:
    branches:
      - main

env:
  DOCKER_API_VERSION: '1.44'

jobs:
  deploy:
    runs-on: dokploy-x64
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Setup Registry
        run: |
          REGISTRY=ghcr.io/${{ github.repository }}
          echo "REGISTRY=${REGISTRY@L}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mintoolkit
        run: |
          URL="https://github.com/mintoolkit/mint/releases/download/1.41.8/dist_linux.tar.gz"

          if [[ $(uname -m) == arm64 || $(uname -m) == aarch64 ]]; then
            URL="https://github.com/mintoolkit/mint/releases/download/1.41.8/dist_linux_arm64.tar.gz"
          fi

          curl -L -o ds.tar.gz $URL
          tar -xvf ds.tar.gz
          mv dist_linux/mint ${{ runner.temp }}
          mv dist_linux/mint-sensor ${{ runner.temp }}
          echo "SLIM_PATH=${{ runner.temp }}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v5
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          platforms: linux/arm64,linux/amd64
          tags: ${{ env.REGISTRY }}:latest,${{ env.REGISTRY }}:${{ github.sha }}
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache

      - name: Slim latest Image
        run: |
          $SLIM_PATH/mint build \
            --http-probe=false \
            --continue-after=1s \
            --tag=${{ env.REGISTRY }}:latest \
            ${{ env.REGISTRY }}:latest

      - name: Slim sha Image
        run: |
          $SLIM_PATH/mint build \
            --http-probe=false \
            --continue-after=1s \
            --tag=${{ env.REGISTRY }}:${{ github.sha }} \
            ${{ env.REGISTRY }}:${{ github.sha }}

      - name: Push Image
        run: docker image push "${{ env.REGISTRY }}" --all-tags

      - name: Start SSH agent and add deploy key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Update image
        env:
          GH_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODES: ${{ vars.NODES }}
          IMAGE: ${{ vars.IMAGE }}
        run: |
          ./prepull.sh
