name: Deploy Image to GHCR

on:
  push:
    branches:
      - main

env:
  DOCKER_API_VERSION: '1.44'

jobs:
  deploy:
    runs-on: dokploy-x64
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Setup Registry
        run: |
          REGISTRY=ghcr.io/${{ github.repository }}
          echo "REGISTRY=${REGISTRY@L}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          platforms: linux/arm64,linux/amd64
          tags: ${{ env.REGISTRY }}:latest,${{ env.REGISTRY }}:${{ github.sha }}

      - name: Slim latest Image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROVE: false
        with:
          target: ${{ env.REGISTRY }}:latest
          overwrite: true
          tag: "latest"

      - name: Slim sha Image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROVE: false
        with:
          target: "${{ env.REGISTRY }}:${{ github.sha }}"
          overwrite: true
          tag: "${{ github.sha }}"

      - name: Push Image
        run: docker image push "${{ env.REGISTRY }}" --all-tags

      - name: Start SSH agent and add deploy key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Update image
        env:
          GH_USERNAME: ${{ github.actor }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODES: ${{ vars.NODES }}
          IMAGE: ${{ vars.IMAGE }}
        run: |
          ./prepull.sh
